### ISSUE TITLE
Client-side validation checks.

### ISSUE THREAD

**Issue by matthewhammer** [nomeata/motoko-certified-http#1]
Nice example repo!

I noticed that the repo provides the service side (producing the certification data) but omits the client side (consuming the certification data).

Would it make sense to add that client side here, or would that go beyond the scope of the repo?

Also, I was wondering if any of the existing SDK JS checking code could be re-used, since you re-used the state tree ("hash tree") representation?

Finally, I'm wondering about a general guideline for canisters that implement certified queries.  This concern is beyond the scope of the example, but the example raises the question for me in a nice, concrete way.

My question is whether a very paranoid consumer of this data would need to always refer to the certified data after checking its proof object, and ignore the other (uncertified) message text data that comes from the queries' results.

My rationale is that if we are paranoid enough to consider the canister queries as coming through an untrusted intermediary, then we must also assume that this intermediary changes _all of the data_ **except** what can be observed as changed by these client checks.

In this case, the paranoid user would want a client that treats the server as as an adversary that lies whenever it can; the client protects the human user from even hearing these lies by actively redacting all of the (query) output that is not derived from certified header data, or certified directly by some check of that data.

In this case, the client would redact the field `body`, [here](https://github.com/nomeata/motoko-certified-http/blob/b5dcb04889060436d173a52d68265ee8c8e117ed/main.mo#L88), and would try to re-generate that content from the header.

WDYT?

**Comment by nomeata** [comment]
For HTTP Assets, which this thing is demoing, the client side is not needed here, as the service worker shipped by the boundary node is validating this.

I avoid the term “certified queries”, because we can’t certify queries on the system yet; we can only have (uncertified) queries that return certified data. I’d like to reserve “certified queries” for the feature where the system _really_ certifies arbitrary queries.

I thought about doing an example of a Motoko canister providing certified variables, and doing the client-side checking, maybe using the https://github.com/nomeata/motoko-merkle-tree library. But then I did not feel like writing JS code and rather opted to investigate Base64 and CBOR instead :-)

> My question is whether a very paranoid consumer of this data would need to always refer to the certified data after checking its proof object, and ignore the other (uncertified) message text data that comes from the queries' results.
 
Yes, of course! (Unless the proof object contains a hash of the other data, of course.)

> by actively redacting all of the (query) output that is not derived from certified header data

Right! And that’s actually what’s happening with the client used here, i.e. the service worker! If you go to https://identity.ic0.app/metrics you never get to see the uncertified body. (Although it does not check headers, which I consider a bug.)

**Comment by matthewhammer** [comment]
> the client side is not needed here, as the service worker shipped by the boundary node is validating this.

Oh, I see.  Now I think that many remaining questions are about the service worker, which I recognize is just a standard thing shared by all IC services.  Thanks for the clarification.

> I avoid the term “certified queries”, because we can’t certify queries on the system yet; we can only have (uncertified) queries that return certified data. I’d like to reserve “certified queries” for the feature where the system really certifies arbitrary queries.

That makes sense.  I'm starting to finally appreciate the subtle differences here.  This example helped a lot, in fact.

> I thought about doing an example of a Motoko canister providing certified variables...But then I did not feel like writing JS code...

Totally understandable.  My head always goes to some admittedly complex design space where we have a true DSL within Motoko to create and inspect certified data, perhaps with a special type connective, like "Authenticated data types, generically".  

Then, we follow part of your Universal Query Certification document from 2021-01 where the checker is part of the canister's registered code, stored on the system but executed locally (unlike the canister's existing Wasm code).

I know those design impulses are out of step with the KISS stance of Motoko thus far, and probably won't be part of any near-term or even medium-term roadmap.  OTOH, if we truly want a PL that supports "certified queries" (as you want to use the term, and I agree), it seems like we need something "advanced" (hopefully not too complex), as the problem seems to demand it.

In any case, I'm interested to hear more of your thoughts about this, perhaps synchronously sometime soon.

**Comment by matthewhammer** [comment]
In any case, we can close this issue.
